[project]
name = "football-predictor"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.110.3",
    "uvicorn[standard]==0.30.1",
    "pydantic==2.8.2",
    "pydantic-settings==2.3.3",
    "xgboost==2.0.3",
    "pandas==2.2.2",
    "numpy==1.26.4",
    "psycopg[binary]",
    "sqlalchemy==2.0.31",
    "prefect",
    "prometheus-client",
    "httpx==0.27.0",
    "beautifulsoup4",
    "structlog",
    "pytest==8.2.1",
    "pytest-cov==5.0.0",
    "scipy==1.13.1",
    "scikit-learn==1.4.2",
    "alembic==1.13.1",
    "psycopg2-binary==2.9.9",
    "aiosqlite==0.20.0",
    "python-dotenv==1.0.1",
    "requests==2.32.3",
    "types-requests==2.32.0.20240712",
    "types-urllib3==1.26.25.14",
    "mypy==1.10.0",
    "ruff==0.5.5",
    "bandit==1.7.9",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "W", "C90", "I"]
ignore = ["E501"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
strict = false
check_untyped_defs = true

[tool.pytest.ini_options]
addopts = "-q --maxfail=1 --cov=. --cov-report=term-missing --cov-fail-under=20 -m 'not integration'"
testpaths = ["tests"]
markers = [
    "integration: tests requiring live database connection"
]

[tool.coverage.run]
source = ["apps", "data_pipeline", "models"]
omit = [
    "*/tests/*",
    "*/test_*.py",
    "*/__pycache__/*",
    "*/.*",
    "setup.py",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
] 
