[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "football-predict-system"
version = "0.1.0"
description = "Football match outcome prediction system"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastapi>=0.100.0",
    "uvicorn[standard]>=0.23.0",
    "pydantic>=2.0.0",
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "scikit-learn>=1.3.0",
    "xgboost>=1.7.0",
    "psycopg2-binary>=2.9.0",
    "sqlalchemy>=2.0.0",
    "prefect>=2.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "pytest-asyncio>=0.21.0",
    "ruff>=0.4.0",
    "mypy>=1.5.0",
    "bandit>=1.7.0",
    "pre-commit>=3.0.0",
    "types-setuptools",
    "diff-cover>=7.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["apps", "data_pipeline", "models", "trainer", "infra", "evaluation"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q -ra -m 'not slow'"
markers = [
    "slow: marks tests as slow (deselected by default)",
    "integration: marks tests as integration tests",
]

[tool.coverage.run]
source = ["."]
omit = ["tests/*", ".venv/*", "*/site-packages/*"]

[tool.coverage.report]
exclude_lines = ["pragma: no cover"]

[tool.ruff]
target-version = "py38"
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W", "I", "B", "UP", "RUF"]
ignore = ["E501", "B008", "B904"]


# 更新后的MyPy配置
[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true

# 只检查我们的源代码，忽略第三方库
files = ["apps", "data_pipeline", "models", "trainer", "infra", "evaluation"]
exclude = [
    ".venv",
    "build",
    "dist",
    "tests"
]

# 忽略第三方库的类型检查
[[tool.mypy.overrides]]
module = [
    "prefect.*",
    "pandas.*", 
    "sklearn.*",
    "xgboost.*",
    "httpx.*",
    "ruamel.*",
    "structlog.*",
    "psycopg2.*",
    "sqlalchemy.*",
    "uvicorn.*",
    "fastapi.*",
    "pydantic.*",
    "starlette.*"
]
ignore_errors = true
ignore_missing_imports = true
