"""
项目常量定义

用于替代代码中的魔法数字, 提高代码可读性和可维护性。
"""


# HTTP状态码常量
class HTTPStatus:
    OK = 200
    BAD_REQUEST = 400
    NOT_FOUND = 404
    METHOD_NOT_ALLOWED = 405
    UNPROCESSABLE_ENTITY = 422
    INTERNAL_SERVER_ERROR = 500
    SERVICE_UNAVAILABLE = 503


# API相关常量
class APIDefaults:
    DEFAULT_PORT = 8000
    REQUEST_TIMEOUT = 30
    MAX_RETRIES = 3


# 测试相关常量
class TestConstants:
    # 性能测试相关
    PERFORMANCE_TOLERANCE = 0.001
    SLOW_QUERY_THRESHOLD_MS = 1000.0
    FAST_QUERY_THRESHOLD_MS = 500.0
    SUPER_SLOW_THRESHOLD_MS = 2500.0
    DURATION_HALF_SECOND = 0.5
    DURATION_TWO_HALF_SECONDS = 2.5

    # 特征向量长度
    FEATURE_VECTOR_LENGTH = 6

    # 测试数据值
    HOME_STRENGTH_SAMPLE = 0.7
    HOME_ODDS_SAMPLE = 1.8
    ODDS_THRESHOLD = 1.5

    # 批量处理
    BATCH_SIZE_TINY = 2
    BATCH_SIZE_SMALL = 3
    BATCH_SIZE_MEDIUM = 5
    BATCH_SIZE_LARGE = 10

    # 时间相关
    TIMEOUT_SECONDS_SHORT = 5
    TIMEOUT_SECONDS_MEDIUM = 60
    TIMEOUT_SECONDS_LONG = 120
    ACCESS_TOKEN_EXPIRE_MINUTES = 20

    # 神经网络相关
    MAGIC_NUMBER_42 = 42

    # 缓存和性能测试
    CACHE_SIZE_SMALL = 8
    CACHE_EXPIRY_SHORT = 5
    CACHE_EXPIRY_LONG = 1800
    CACHE_TTL_STANDARD = 3600

    # 数据质量
    ACCURACY_THRESHOLD = 0.8
    SAMPLE_COUNT = 1000

    # 负载测试
    LOAD_TEST_LIGHT = 2000
    LOAD_TEST_HEAVY = 5000

    # 精度测试
    PRECISION_TEST = 0.01


# 健康检查相关常量
class HealthConstants:
    LATENCY_MS_HEALTHY = 50
    COMPONENT_COUNT_FULL = 5


# 缓存相关常量
class CacheConstants:
    DEFAULT_TTL = 300  # 5分钟
    TIMESTAMP_SAMPLE = 1234567890.123


# 数据库相关常量
class DatabaseConstants:
    CONNECTION_POOL_SIZE = 10
    QUERY_TIMEOUT = 30
