apiVersion: v1
kind: Namespace
metadata:
  name: football-system
  labels:
    name: football-system
    env: production

---
apiVersion: v1
kind: Secret
metadata:
  name: football-secrets
  namespace: football-system
type: Opaque
stringData:
  database-url: "postgresql+asyncpg://postgres:password@postgres:5432/football_predict"
  redis-url: "redis://redis:6379/0"
  jwt-secret: "your-super-secret-jwt-key-change-this-in-production"
  api-key: "your-football-api-key-here"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: football-api
  namespace: football-system
  labels:
    app: football-api

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: football-system
  name: football-api-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: football-api-binding
  namespace: football-system
subjects:
  - kind: ServiceAccount
    name: football-api
    namespace: football-system
roleRef:
  kind: Role
  name: football-api-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: football-models-pvc
  namespace: football-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storage
