# Football Data Platform Prometheus Configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # Football Predict System API
  - job_name: "football-predict-api"
    static_configs:
      - targets: ["localhost:8000"]
    metrics_path: "/metrics"
    scrape_interval: 30s
    scrape_timeout: 10s

  # Data Platform Metrics
  - job_name: "data-platform-metrics"
    static_configs:
      - targets: ["localhost:8090"]
    metrics_path: "/metrics"
    scrape_interval: 60s

  # PostgreSQL Database Metrics
  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["localhost:9187"]
    scrape_interval: 30s

  # Redis Cache Metrics
  - job_name: "redis-exporter"
    static_configs:
      - targets: ["localhost:9121"]
    scrape_interval: 30s

  # Node Exporter for System Metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["localhost:9100"]
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
