# AI-Fix-Enhancement: Workflow to automatically create a PR from an AI-generated fix

name: AI-Fix Create PR

on:
  workflow_dispatch:
    inputs:
      bug_description:
        description: 'The description of the bug being fixed'
        required: true
        default: 'A bug that needs fixing'
      fix_patch:
        description: 'Base64 encoded patch file for the fix'
        required: true

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Apply AI-Generated Patch
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          echo "${{ inputs.fix_patch }}" | base64 --decode > ai_fix.patch
          git apply ai_fix.patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "fix(ai): Apply automated fix for bug"
          branch: ai-fix/${{ github.run_id }}-${{ github.run_number }}
          delete-branch: true
          title: '[AI-Fix] ${{ inputs.bug_description }}'
          body: |
            This PR was automatically generated by the AI-Fix workflow.

            **Bug Description:**
            ${{ inputs.bug_description }}

            **Proposed Fix:**
            The applied patch is attached to this PR.

            Please review the changes carefully before merging.
          labels: |
            ai-fix
            bug
          assignees: 'your-github-username' # Replace with a default assignee
          reviewers: 'your-github-username' # Replace with default reviewers
