name: "Gitleaks"
on:
  push: { branches: ["main","dev"] }
  pull_request: { branches: ["main","dev"] }
jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --redact 