# AI-Fix-Enhancement: Workflow to notify on AI-Fix PR status changes

name: Notify on AI-Fix PR Status

on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    # Only run this job if the PR has the 'ai-fix' label
    if: contains(github.event.pull_request.labels.*.name, 'ai-fix')
    steps:
      - name: Determine PR Status and Color
        id: pr_status
        run: |
          if [[ "${{ github.event.action }}" == "opened" || "${{ github.event.action }}" == "reopened" ]]; then
            echo "STATUS_MESSAGE=🚀 New AI-Fix PR needs review" >> $GITHUB_ENV
            echo "MESSAGE_COLOR=warning" >> $GITHUB_ENV
          elif [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "STATUS_MESSAGE=✅ AI-Fix PR has been merged" >> $GITHUB_ENV
            echo "MESSAGE_COLOR=info" >> $GITHUB_ENV
          else
            echo "STATUS_MESSAGE=❌ AI-Fix PR was closed without merging" >> $GITHUB_ENV
            echo "MESSAGE_COLOR=comment" >> $GITHUB_ENV
          fi

      - name: Send Notification to Webhook
        uses: navatech/wechat-work-webhook-action@v1.1.0
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }} # IMPORTANT: Configure this secret in your repo settings
          msg_type: markdown
          content: |
            **${{ env.STATUS_MESSAGE }}**
            **PR:** <font color="${{ env.MESSAGE_COLOR }}">[${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})</font>
            **Repo:** ${{ github.repository }}
            **Author:** @${{ github.actor }}
            **Status:** ${{ github.event.action }}
